// main.js
import './assets/utils/prevent-copy.js';
import './assets/utils/navhide.js';
import './assets/utils/burger.js';
import './assets/utils/smooth-scroll.js';
import './assets/lib/email.js';
import './assets/lib/masonry.js';
import './assets/utils/reveal.js';
import './assets/utils/apropos-reveal.js';
import './assets/utils/maxime-reveal.js';
import './assets/utils/parallax.js';
import './assets/utils/modal-mentions.js';
import './assets/lib/gallery.js';